# Headless test bench for the PERSONAL.XLSB "Cleaning" macro. Imports a stubbed copy of the
# module (Cleaning_Test.bas, generated by gen.py) plus the real CleaningForm into a throwaway
# workbook, runs the macro over the case table for every option set, and dumps what Excel
# actually holds afterwards. Nothing is saved; no file on disk is touched.
param(
    [Parameter(Mandatory)][string]$AuditDir,   # holds Cleaning_Test.bas, cases.csv, opts.csv
    [Parameter(Mandatory)][string]$FormDir     # holds CleaningForm.frm + .frx
)
$ErrorActionPreference = 'Stop'
# COM Import/Export resolve relative paths against Excel's own working directory, not ours
$AuditDir = (Resolve-Path -LiteralPath $AuditDir).Path
$FormDir  = (Resolve-Path -LiteralPath $FormDir).Path

function Unesc([string]$s) {
    $s.Replace('{LF}', "`n").Replace('{CR}', "`r").Replace('{TAB}', "`t").Replace('{NBSP}', [string][char]0xA0).Replace('{ZWSP}', [string][char]0x200B).Replace('{ZWNJ}', [string][char]0x200C).Replace('{ZWJ}', [string][char]0x200D).Replace('{BOM}', [string][char]0xFEFF).Replace('{ENSP}', [string][char]0x2002).Replace('{THIN}', [string][char]0x2009).Replace('{IDEO}', [string][char]0x3000).Replace('{WJ}', [string][char]0x2060).Replace('{LSEP}', [string][char]0x2028).Replace('{PSEP}', [string][char]0x2029).Replace('{OGH}', [string][char]0x1680)
}
function Esc([string]$s) {
    $s.Replace("`r", '{CR}').Replace("`n", '{LF}').Replace("`t", '{TAB}').Replace([string][char]0xA0, '{NBSP}').Replace([string][char]0x200B, '{ZWSP}').Replace([string][char]0x200C, '{ZWNJ}').Replace([string][char]0x200D, '{ZWJ}').Replace([string][char]0xFEFF, '{BOM}').Replace([string][char]0x2002, '{ENSP}').Replace([string][char]0x2009, '{THIN}').Replace([string][char]0x3000, '{IDEO}').Replace([string][char]0x2060, '{WJ}').Replace([string][char]0x2028, '{LSEP}').Replace([string][char]0x2029, '{PSEP}').Replace([string][char]0x1680, '{OGH}')
}
function Csv([string]$s) {
    if ($s -match '[",\r\n]') { '"' + ($s -replace '"', '""') + '"' } else { $s }
}
$utf8 = New-Object System.Text.UTF8Encoding($true)
# Cyrillic letters by code point, so this file stays pure ASCII (no BOM trap)
$cyrR = [string][char]0x0420; $cyrA = [string][char]0x0410; $cyrB = [string][char]0x0412
$cyrO = [string][char]0x041E; $cyrT = [string][char]0x0422
# ru-RU quirk (Probe-RangeQuirks.ps1): NumberFormat='General' throws here; the localized name works
$fmtGeneral = -join ([char]0x041E,[char]0x0441,[char]0x043D,[char]0x043E,[char]0x0432,[char]0x043D,[char]0x043E,[char]0x0439)
$log = New-Object System.Collections.Generic.List[string]
function Log([string]$s) { $script:log.Add($s); Write-Output $s }

$cases = Import-Csv (Join-Path $AuditDir 'cases.csv') -Encoding UTF8
$opts  = Import-Csv (Join-Path $AuditDir 'opts.csv')  -Encoding UTF8

$excel = $null; $wb = $null
try {
    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $false; $excel.DisplayAlerts = $false
    $wb = $excel.Workbooks.Add()
    [void]$wb.VBProject.VBComponents.Import((Join-Path $AuditDir 'Cleaning_Test.bas'))
    [void]$wb.VBProject.VBComponents.Import((Join-Path $FormDir  'CleaningForm.frm'))
    Log "imported: $(($wb.VBProject.VBComponents | ForEach-Object { $_.Name }) -join ', ')"

    function Fresh([string]$name) {
        $s = $script:wb.Worksheets.Add()
        $s.Name = $name
        $s.Activate()
        return $s
    }
    function RunMacro($c1, $c2, $c3, $c4) {
        return [string]$script:excel.Run('Cleaning_Test.RunTest', [bool]$c1, [bool]$c2, [bool]$c3, [bool]$c4)
    }

    # ---------------- matrix: cases x option sets ----------------
    $rows = New-Object System.Collections.Generic.List[string]
    $rows.Add('opt,id,actual')
    foreach ($o in $opts) {
        $ws = Fresh ("M_" + $o.opt)
        $r = 2
        foreach ($c in $cases) {
            $cell = $ws.Range("B$r")
            $cell.NumberFormat = '@'
            $cell.Value2 = (Unesc $c.input)
            $ws.Range("A$r").Value2 = $c.id
            $r++
        }
        $last = $r - 1
        $ws.Range("B2:B$last").Select() | Out-Null
        $msg = RunMacro ($o.c1 -eq '1') ($o.c2 -eq '1') ($o.c3 -eq '1') ($o.c4 -eq '1')
        Log ("[{0}] stats: {1}" -f $o.opt, ($msg -replace "`r`n", ' | '))
        $r = 2
        foreach ($c in $cases) {
            $v = $ws.Range("B$r").Value2
            $rows.Add(("{0},{1},{2}" -f $o.opt, $c.id, (Csv (Esc ([string]$v)))))
            $r++
        }
    }
    [IO.File]::WriteAllText((Join-Path $AuditDir 'results.csv'), ($rows -join "`r`n") + "`r`n", $utf8)

    # ---------------- special cases ----------------
    function Probe([string]$name, [scriptblock]$body) {
        try { $out = & $body; Log ("{0}: OK {1}" -f $name, $out) }
        catch { Log ("{0}: EXCEPTION {1}" -f $name, ($_.Exception.Message -replace "\s+", ' ')) }
        Log ("{0}: Application.ScreenUpdating after = {1}" -f $name, $script:excel.ScreenUpdating)
        $script:excel.ScreenUpdating = $true
    }

    Probe 'T_general_format_writeback' {
        $ws = Fresh 'T_general'
        $inputs = @('00123 ', '1.2 ', '1,5 ', '1E5 ', '12/03 ', 'TRUE ', '-7 ', '10-12 ', '3.3.5 ', '(5) ')
        $r = 2
        # store as TEXT (like a Power Query output column), then put the cell back on General - the realistic shape
        foreach ($s in $inputs) { $c = $ws.Range("B$r"); $c.NumberFormat = '@'; $c.Value2 = $s; $c.NumberFormatLocal = $fmtGeneral; $r++ }
        $last = $r - 1
        $before = @(); $r = 2
        foreach ($s in $inputs) { $before += ('{0}=>{1}({2})' -f $s.Trim(), $ws.Range("B$r").Value2, $ws.Range("B$r").Value2.GetType().Name); $r++ }
        $ws.Range("B2:B$last").Select() | Out-Null
        $msg = RunMacro $false $false $true $false        # remove all spaces -> forces a write-back
        $after = @(); $r = 2
        foreach ($s in $inputs) {
            $c = $ws.Range("B$r")
            $after += ('{0}=>[{1}] type={2} text=[{3}] fmt=[{4}]' -f $s.Trim(), $c.Value2, $c.Value2.GetType().Name, $c.Text, $c.NumberFormat)
            $r++
        }
        "`n  before: " + ($before -join '; ') + "`n  after:  " + ($after -join "`n          ")
    }

    Probe 'T_non_text_cells' {
        $ws = Fresh 'T_types'
        $ws.Range('B2').Value2 = 1.5
        $ws.Range('B3').Value2 = 46286; $ws.Range('B3').NumberFormat = 'dd.mm.yyyy'
        $ws.Range('B4').Value2 = $true
        $ws.Range('B6').Formula = '=1+1'
        $ws.Range('B7').Value2 = 42
        $ws.Range('B8').NumberFormat = '@'; $ws.Range('B8').Value2 = ('AB1 ' + $cyrR + ' C')   # control cell
        $ws.Range('B2:B8').Select() | Out-Null
        $msg = RunMacro $true $true $false $true
        $s = @()
        foreach ($a in 'B2','B3','B4','B5','B6','B7','B8') { $c = $ws.Range($a); $s += ('{0}=[{1}] formula={2}' -f $a, $c.Value2, $c.HasFormula) }
        ($s -join '; ') + ' | stats: ' + ($msg -replace "`r`n", ' | ')
    }

    Probe 'T_formula_NA_in_selection' {
        $ws = Fresh 'T_na_f'
        $ws.Range('B2').NumberFormat = '@'; $ws.Range('B2').Value2 = 'abc'
        $ws.Range('B3').Formula = '=NA()'
        $ws.Range('B2:B3').Select() | Out-Null
        RunMacro $true $true $false $true
    }

    Probe 'T_literal_NA_in_selection' {
        $ws = Fresh 'T_na_l'
        $ws.Range('B2').NumberFormat = '@'; $ws.Range('B2').Value2 = 'abc'
        $ws.Range('B3').Formula = '#N/A'
        $ws.Range('B2:B3').Select() | Out-Null
        'B3.HasFormula=' + $ws.Range('B3').HasFormula + ' ; ' + (RunMacro $true $true $false $true)
    }

    Probe 'T_32767_chars' {
        $ws = Fresh 'T_long'
        $s = '1' + $cyrR + ('x' * 32765)   # 32767 chars = Excel cell maximum; code-like (digit + Latin)
        $ws.Range('B2').NumberFormat = '@'; $ws.Range('B2').Value2 = $s
        $ws.Range('B2').Select() | Out-Null
        'len=' + $ws.Range('B2').Value2.Length + ' ; ' + (RunMacro $true $false $false $false)
    }

    Probe 'T_ctrl_A_whole_sheet' {
        $ws = Fresh 'T_ctrlA'
        $ws.Range('B2').NumberFormat = '@'; $ws.Range('B2').Value2 = ('AB1 ' + $cyrR)
        $ws.Cells.Select() | Out-Null
        RunMacro $true $false $false $false
    }

    Probe 'T_merged_cells' {
        $ws = Fresh 'T_merged'
        $ws.Range('B2:C2').Merge()
        $ws.Range('B2').NumberFormat = '@'; $ws.Range('B2').Value2 = ('AB' + $cyrR + '1')
        $ws.Range('B2:C2').Select() | Out-Null
        $msg = RunMacro $true $false $false $false
        'B2=[' + $ws.Range('B2').Value2 + '] ' + ($msg -replace "`r`n", ' | ')
    }

    Probe 'T_multi_area_selection' {
        $ws = Fresh 'T_multi'
        foreach ($a in 'B2','B3','D2','D3') { $ws.Range($a).NumberFormat = '@'; $ws.Range($a).Value2 = ('AB1' + $cyrR) }
        $ws.Range('B2:B3;D2:D3').Select() | Out-Null   # ru-RU: list separator is ';' through COM
        $msg = RunMacro $true $false $false $false
        'B2=[' + $ws.Range('B2').Value2 + '] D2=[' + $ws.Range('D2').Value2 + '] ' + ($msg -replace "`r`n", ' | ')
    }

    Probe 'T_protected_sheet' {
        $ws = Fresh 'T_prot'
        $ws.Range('B2').NumberFormat = '@'; $ws.Range('B2').Value2 = ('AB1' + $cyrR)
        $ws.Protect() | Out-Null
        $ws.Range('B2').Select() | Out-Null
        RunMacro $true $false $false $false
    }

    Probe 'T_rich_text' {
        $ws = Fresh 'T_rich'
        $ws.Range('B2').NumberFormat = '@'; $ws.Range('B2').Value2 = ($cyrR + $cyrA + $cyrB + $cyrO + $cyrT + $cyrA)
        $ws.Range('B2').Characters(1, 1).Font.Bold = $true
        $b1 = $ws.Range('B2').Characters(1, 1).Font.Bold; $b2 = $ws.Range('B2').Characters(2, 1).Font.Bold
        $ws.Range('B2').Select() | Out-Null
        $msg = RunMacro $true $false $false $false
        'bold(1) before=' + $b1 + ' after=' + $ws.Range('B2').Characters(1, 1).Font.Bold + ' ; bold(2) before=' + $b2 + ' after=' + $ws.Range('B2').Characters(2, 1).Font.Bold + ' ; value=[' + $ws.Range('B2').Value2 + ']'
    }

    Probe 'T_formula_injection_from_text' {
        $ws = Fresh 'T_inj'
        $c = $ws.Range('B2'); $c.NumberFormat = '@'; $c.Value2 = '=1 +  1'; $c.NumberFormatLocal = $fmtGeneral
        $before = 'before: value=[' + $c.Value2 + '] formula=' + $c.HasFormula
        $ws.Range('B2').Select() | Out-Null
        $msg = RunMacro $false $false $false $true      # normalise spaces -> "=1 + 1" written back
        $before + ' ; after: value=[' + $c.Value2 + '] formula=' + $c.HasFormula + ' Formula=[' + $c.Formula + ']'
    }

    Probe 'T_datetime_remove_spaces' {
        $ws = Fresh 'T_dt'
        $c = $ws.Range('B2'); $c.Value = [datetime]'2026-09-21 12:00'   # a real Date variant -> Excel applies a date-time format itself
        $before = 'before: value=[' + $c.Value2 + '] type=' + $c.Value2.GetType().Name + ' text=[' + $c.Text + ']'
        $ws.Range('B2').Select() | Out-Null
        $msg = RunMacro $false $false $true $false      # remove all spaces
        $before + ' ; after: value=[' + $c.Value2 + '] type=' + $c.Value2.GetType().Name + ' text=[' + $c.Text + ']'
    }

    Probe 'T_linebreak_stats_single_cell' {
        $ws = Fresh 'T_lbstat'
        $c = $ws.Range('B2'); $c.NumberFormat = '@'; $c.Value2 = "A`nB"
        $ws.Range('B2').Select() | Out-Null
        $msg = RunMacro $false $true $false $false
        'after=[' + (Esc ([string]$c.Value2)) + '] stats: ' + ($msg -replace "`r`n", ' | ')
    }

    Probe 'T_form_close_X' {
        [string]$script:excel.Run('Cleaning_Test.ProbeCloseX')
    }

    Probe 'T_fix_safe_write_roundtrip' {
        $ws = Fresh 'T_fix'
        $out = @()
        $r = 2
        foreach ($v in '00123', '1.2', '1E5', '12/03', '=1 + 1', 'TRUE') {
            $c = $ws.Range("B$r")     # General cell, as in real sheets
            $out += ($v + ' -> ' + [string]$script:excel.Run('Cleaning_Test.ProbeSafeWrite', $c, $v))
            $r++
        }
        "`n  " + ($out -join "`n  ")
    }

    Probe 'T_single_cell_selection' {
        # SpecialCells on a one-cell range silently expands to the whole sheet: D5 must stay untouched
        $ws = Fresh 'T_one'
        foreach ($a in 'B2','D5') { $ws.Range($a).NumberFormat = '@'; $ws.Range($a).Value2 = ('AB1' + $cyrR) }
        $ws.Range('B2').Select() | Out-Null
        $msg = RunMacro $true $false $false $false
        'B2=[' + $ws.Range('B2').Value2 + '] D5=[' + $ws.Range('D5').Value2 + '] ' + ($msg -replace "`r`n", ' | ')
    }

    Probe 'T_hidden_row' {
        $ws = Fresh 'T_hidden'
        foreach ($a in 'B2','B3','B4') { $ws.Range($a).NumberFormat = '@'; $ws.Range($a).Value2 = ('AB1' + $cyrR) }
        $ws.Rows(3).Hidden = $true
        $ws.Range('B2:B4').Select() | Out-Null
        $msg = RunMacro $true $false $false $false
        'B2=[' + $ws.Range('B2').Value2 + '] B3(hidden)=[' + $ws.Range('B3').Value2 + '] B4=[' + $ws.Range('B4').Value2 + '] ' + ($msg -replace "`r`n", ' | ')
    }

    Probe 'T_whole_column_timing' {
        $ws = Fresh 'T_col'
        for ($r = 2; $r -le 21; $r++) { $ws.Range("B$r").NumberFormat = '@'; $ws.Range("B$r").Value2 = ('AB1 ' + $cyrR + ' C') }
        $ws.Range('B:B').Select() | Out-Null
        $sw = [Diagnostics.Stopwatch]::StartNew()
        $msg = RunMacro $true $false $false $false
        $sw.Stop()
        ('{0:N1} s for 1,048,576 cells (20 with data); stats: {1}' -f $sw.Elapsed.TotalSeconds, ($msg -replace "`r`n", ' | '))
    }
}
finally {
    if ($wb)    { $wb.Close($false) }
    if ($excel) { $excel.Quit() }
    foreach ($o in @($wb, $excel)) { if ($o) { [void][Runtime.InteropServices.Marshal]::ReleaseComObject($o) } }
    [GC]::Collect(); [GC]::WaitForPendingFinalizers()
    [IO.File]::WriteAllText((Join-Path $AuditDir 'special.txt'), ($log -join "`r`n") + "`r`n", $utf8)
}
